"""empty message

Revision ID: 0f45f186d8e5
Revises: 71616399c209
Create Date: 2016-11-10 13:27:24.774402

"""

# revision identifiers, used by Alembic.
revision = '0f45f186d8e5'
down_revision = '71616399c209'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    ### end Alembic commands ###
