"""empty message

Revision ID: 30d3a6989c9c
Revises: 0f45f186d8e5
Create Date: 2016-11-13 14:20:49.747580

"""

# revision identifiers, used by Alembic.
revision = '30d3a6989c9c'
down_revision = '0f45f186d8e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_at')
    ### end Alembic commands ###
