"""empty message

Revision ID: 71616399c209
Revises: 032c7ce6c97a
Create Date: 2016-11-10 13:26:53.395747

"""

# revision identifiers, used by Alembic.
revision = '71616399c209'
down_revision = '032c7ce6c97a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    ### end Alembic commands ###
