"""empty message

Revision ID: 893d00964f86
Revises: 3bc94e44b920
Create Date: 2016-11-09 21:25:17.029231

"""

# revision identifiers, used by Alembic.
revision = '893d00964f86'
down_revision = '3bc94e44b920'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    ### end Alembic commands ###
